spring.application.name=workflow-service

spring.datasource.url=jdbc:postgresql://postgres:5432/workflowdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

server.port=8080

spring.kafka.bootstrap-servers=kafka:9092